/**
 * Built-in Mythos themes — ported from OpenCode's JSON theme files.
 */
import type { ThemeDefinition, MythosTheme, MythosThemeName } from './types.js'
import { resolveTheme } from './resolve.js'

// ── OpenCode (default) ─────────────────────────────────────────────────
const opencode: ThemeDefinition = {
  defs: {
    darkStep1: '#0a0a0a', darkStep2: '#141414', darkStep3: '#1e1e1e',
    darkStep4: '#282828', darkStep5: '#323232', darkStep6: '#3c3c3c',
    darkStep7: '#484848', darkStep8: '#606060', darkStep9: '#fab283',
    darkStep10: '#ffc09f', darkStep11: '#808080', darkStep12: '#eeeeee',
    darkSecondary: '#5c9cf5', darkAccent: '#9d7cd8',
    darkRed: '#e06c75', darkOrange: '#f5a742', darkGreen: '#7fd88f',
    darkCyan: '#56b6c2', darkYellow: '#e5c07b',
    lightStep1: '#ffffff', lightStep2: '#fafafa', lightStep3: '#f5f5f5',
    lightStep4: '#ebebeb', lightStep5: '#e1e1e1', lightStep6: '#d4d4d4',
    lightStep7: '#b8b8b8', lightStep8: '#a0a0a0', lightStep9: '#3b7dd8',
    lightStep10: '#2968c3', lightStep11: '#8a8a8a', lightStep12: '#1a1a1a',
    lightSecondary: '#7b5bb6', lightAccent: '#d68c27',
    lightRed: '#d1383d', lightOrange: '#d68c27', lightGreen: '#3d9a57',
    lightCyan: '#318795', lightYellow: '#b0851f',
  },
  theme: {
    primary: { dark: 'darkStep9', light: 'lightStep9' },
    secondary: { dark: 'darkSecondary', light: 'lightSecondary' },
    accent: { dark: 'darkAccent', light: 'lightAccent' },
    error: { dark: 'darkRed', light: 'lightRed' },
    warning: { dark: 'darkOrange', light: 'lightOrange' },
    success: { dark: 'darkGreen', light: 'lightGreen' },
    info: { dark: 'darkCyan', light: 'lightCyan' },
    text: { dark: 'darkStep12', light: 'lightStep12' },
    textMuted: { dark: 'darkStep11', light: 'lightStep11' },
    background: { dark: 'darkStep1', light: 'lightStep1' },
    backgroundPanel: { dark: 'darkStep2', light: 'lightStep2' },
    backgroundElement: { dark: 'darkStep3', light: 'lightStep3' },
    border: { dark: 'darkStep7', light: 'lightStep7' },
    borderActive: { dark: 'darkStep8', light: 'lightStep8' },
    borderSubtle: { dark: 'darkStep6', light: 'lightStep6' },
    diffAdded: { dark: '#4fd6be', light: '#1e725c' },
    diffRemoved: { dark: '#c53b53', light: '#c53b53' },
    diffContext: { dark: '#828bb8', light: '#7086b5' },
    diffHunkHeader: { dark: '#828bb8', light: '#7086b5' },
    diffHighlightAdded: { dark: '#b8db87', light: '#4db380' },
    diffHighlightRemoved: { dark: '#e26a75', light: '#f52a65' },
    diffAddedBg: { dark: '#20303b', light: '#d5e5d5' },
    diffRemovedBg: { dark: '#37222c', light: '#f7d8db' },
    diffContextBg: { dark: 'darkStep2', light: 'lightStep2' },
    diffLineNumber: { dark: 'darkStep3', light: 'lightStep3' },
    diffAddedLineNumberBg: { dark: '#1b2b34', light: '#c5d5c5' },
    diffRemovedLineNumberBg: { dark: '#2d1f26', light: '#e7c8cb' },
    markdownText: { dark: 'darkStep12', light: 'lightStep12' },
    markdownHeading: { dark: 'darkAccent', light: 'lightAccent' },
    markdownLink: { dark: 'darkStep9', light: 'lightStep9' },
    markdownLinkText: { dark: 'darkCyan', light: 'lightCyan' },
    markdownCode: { dark: 'darkGreen', light: 'lightGreen' },
    markdownBlockQuote: { dark: 'darkYellow', light: 'lightYellow' },
    markdownEmph: { dark: 'darkYellow', light: 'lightYellow' },
    markdownStrong: { dark: 'darkOrange', light: 'lightOrange' },
    markdownHorizontalRule: { dark: 'darkStep11', light: 'lightStep11' },
    markdownListItem: { dark: 'darkStep9', light: 'lightStep9' },
    markdownListEnumeration: { dark: 'darkCyan', light: 'lightCyan' },
    markdownImage: { dark: 'darkStep9', light: 'lightStep9' },
    markdownImageText: { dark: 'darkCyan', light: 'lightCyan' },
    markdownCodeBlock: { dark: 'darkStep12', light: 'lightStep12' },
    syntaxComment: { dark: 'darkStep11', light: 'lightStep11' },
    syntaxKeyword: { dark: 'darkAccent', light: 'lightAccent' },
    syntaxFunction: { dark: 'darkStep9', light: 'lightStep9' },
    syntaxVariable: { dark: 'darkRed', light: 'lightRed' },
    syntaxString: { dark: 'darkGreen', light: 'lightGreen' },
    syntaxNumber: { dark: 'darkOrange', light: 'lightOrange' },
    syntaxType: { dark: 'darkYellow', light: 'lightYellow' },
    syntaxOperator: { dark: 'darkCyan', light: 'lightCyan' },
    syntaxPunctuation: { dark: 'darkStep12', light: 'lightStep12' },
  },
}

// ── Catppuccin Mocha (dark default) ─────────────────────────────────────
const catppuccinDefs = {
  darkRosewater: '#f5e0dc', darkFlamingo: '#f2cdcd', darkPink: '#f5c2e7',
  darkMauve: '#cba6f7', darkRed: '#f38ba8', darkMaroon: '#eba0ac',
  darkPeach: '#fab387', darkYellow: '#f9e2af', darkGreen: '#a6e3a1',
  darkTeal: '#94e2d5', darkSky: '#89dceb', darkSapphire: '#74c7ec',
  darkBlue: '#89b4fa', darkLavender: '#b4befe', darkText: '#cdd6f4',
  darkSubtext1: '#bac2de', darkSubtext0: '#a6adc8', darkOverlay2: '#9399b2',
  darkOverlay1: '#7f849c', darkOverlay0: '#6c7086', darkSurface2: '#585b70',
  darkSurface1: '#45475a', darkSurface0: '#313244', darkBase: '#1e1e2e',
  darkMantle: '#181825', darkCrust: '#11111b',
  lightRosewater: '#dc8a78', lightFlamingo: '#dd7878', lightPink: '#ea76cb',
  lightMauve: '#8839ef', lightRed: '#d20f39', lightMaroon: '#e64553',
  lightPeach: '#fe640b', lightYellow: '#df8e1d', lightGreen: '#40a02b',
  lightTeal: '#179299', lightSky: '#04a5e5', lightSapphire: '#209fb5',
  lightBlue: '#1e66f5', lightLavender: '#7287fd', lightText: '#4c4f69',
  lightSubtext1: '#5c5f77', lightSubtext0: '#6c6f85', lightOverlay2: '#7c7f93',
  lightOverlay1: '#8c8fa1', lightOverlay0: '#9ca0b0', lightSurface2: '#acb0be',
  lightSurface1: '#bcc0cc', lightSurface0: '#ccd0da', lightBase: '#eff1f5',
  lightMantle: '#e6e9ef', lightCrust: '#dce0e8',
}

const catppuccin: ThemeDefinition = {
  defs: catppuccinDefs,
  theme: {
    primary: { dark: 'darkBlue', light: 'lightBlue' },
    secondary: { dark: 'darkMauve', light: 'lightMauve' },
    accent: { dark: 'darkPink', light: 'lightPink' },
    error: { dark: 'darkRed', light: 'lightRed' },
    warning: { dark: 'darkYellow', light: 'lightYellow' },
    success: { dark: 'darkGreen', light: 'lightGreen' },
    info: { dark: 'darkTeal', light: 'lightTeal' },
    text: { dark: 'darkText', light: 'lightText' },
    textMuted: { dark: 'darkOverlay2', light: 'lightOverlay2' },
    background: { dark: 'darkBase', light: 'lightBase' },
    backgroundPanel: { dark: 'darkMantle', light: 'lightMantle' },
    backgroundElement: { dark: 'darkCrust', light: 'lightCrust' },
    border: { dark: 'darkSurface0', light: 'lightSurface0' },
    borderActive: { dark: 'darkSurface1', light: 'lightSurface1' },
    borderSubtle: { dark: 'darkSurface2', light: 'lightSurface2' },
    diffAdded: { dark: 'darkGreen', light: 'lightGreen' },
    diffRemoved: { dark: 'darkRed', light: 'lightRed' },
    diffContext: { dark: 'darkOverlay2', light: 'lightOverlay2' },
    diffHunkHeader: { dark: 'darkPeach', light: 'lightPeach' },
    diffHighlightAdded: { dark: 'darkGreen', light: 'lightGreen' },
    diffHighlightRemoved: { dark: 'darkRed', light: 'lightRed' },
    diffAddedBg: { dark: '#24312b', light: '#d6f0d9' },
    diffRemovedBg: { dark: '#3c2a32', light: '#f6dfe2' },
    diffContextBg: { dark: 'darkMantle', light: 'lightMantle' },
    diffLineNumber: { dark: 'darkSurface1', light: 'lightSurface1' },
    diffAddedLineNumberBg: { dark: '#1e2a25', light: '#c9e3cb' },
    diffRemovedLineNumberBg: { dark: '#32232a', light: '#e9d3d6' },
    markdownText: { dark: 'darkText', light: 'lightText' },
    markdownHeading: { dark: 'darkMauve', light: 'lightMauve' },
    markdownLink: { dark: 'darkBlue', light: 'lightBlue' },
    markdownLinkText: { dark: 'darkSky', light: 'lightSky' },
    markdownCode: { dark: 'darkGreen', light: 'lightGreen' },
    markdownBlockQuote: { dark: 'darkYellow', light: 'lightYellow' },
    markdownEmph: { dark: 'darkYellow', light: 'lightYellow' },
    markdownStrong: { dark: 'darkPeach', light: 'lightPeach' },
    markdownHorizontalRule: { dark: 'darkSubtext0', light: 'lightSubtext0' },
    markdownListItem: { dark: 'darkBlue', light: 'lightBlue' },
    markdownListEnumeration: { dark: 'darkSky', light: 'lightSky' },
    markdownImage: { dark: 'darkBlue', light: 'lightBlue' },
    markdownImageText: { dark: 'darkSky', light: 'lightSky' },
    markdownCodeBlock: { dark: 'darkText', light: 'lightText' },
    syntaxComment: { dark: 'darkOverlay2', light: 'lightOverlay2' },
    syntaxKeyword: { dark: 'darkMauve', light: 'lightMauve' },
    syntaxFunction: { dark: 'darkBlue', light: 'lightBlue' },
    syntaxVariable: { dark: 'darkRed', light: 'lightRed' },
    syntaxString: { dark: 'darkGreen', light: 'lightGreen' },
    syntaxNumber: { dark: 'darkPeach', light: 'lightPeach' },
    syntaxType: { dark: 'darkYellow', light: 'lightYellow' },
    syntaxOperator: { dark: 'darkSky', light: 'lightSky' },
    syntaxPunctuation: { dark: 'darkText', light: 'lightText' },
  },
}

// ── Dracula ─────────────────────────────────────────────────────────────
const dracula: ThemeDefinition = {
  defs: {
    background: '#282a36', currentLine: '#44475a', selection: '#44475a',
    foreground: '#f8f8f2', comment: '#6272a4', cyan: '#8be9fd',
    green: '#50fa7b', orange: '#ffb86c', pink: '#ff79c6',
    purple: '#bd93f9', red: '#ff5555', yellow: '#f1fa8c',
  },
  theme: {
    primary: { dark: 'purple', light: 'purple' },
    secondary: { dark: 'pink', light: 'pink' },
    accent: { dark: 'cyan', light: 'cyan' },
    error: { dark: 'red', light: 'red' },
    warning: { dark: 'yellow', light: 'yellow' },
    success: { dark: 'green', light: 'green' },
    info: { dark: 'orange', light: 'orange' },
    text: { dark: 'foreground', light: '#282a36' },
    textMuted: { dark: 'comment', light: '#6272a4' },
    background: { dark: '#282a36', light: '#f8f8f2' },
    backgroundPanel: { dark: '#21222c', light: '#e8e8e2' },
    backgroundElement: { dark: 'currentLine', light: '#d8d8d2' },
    border: { dark: 'currentLine', light: '#c8c8c2' },
    borderActive: { dark: 'purple', light: 'purple' },
    borderSubtle: { dark: '#191a21', light: '#e0e0e0' },
    diffAdded: { dark: 'green', light: 'green' },
    diffRemoved: { dark: 'red', light: 'red' },
    diffContext: { dark: 'comment', light: '#6272a4' },
    diffHunkHeader: { dark: 'comment', light: '#6272a4' },
    diffHighlightAdded: { dark: 'green', light: 'green' },
    diffHighlightRemoved: { dark: 'red', light: 'red' },
    diffAddedBg: { dark: '#1a3a1a', light: '#e0ffe0' },
    diffRemovedBg: { dark: '#3a1a1a', light: '#ffe0e0' },
    diffContextBg: { dark: '#21222c', light: '#e8e8e2' },
    diffLineNumber: { dark: 'currentLine', light: '#c8c8c2' },
    diffAddedLineNumberBg: { dark: '#1a3a1a', light: '#e0ffe0' },
    diffRemovedLineNumberBg: { dark: '#3a1a1a', light: '#ffe0e0' },
    markdownText: { dark: 'foreground', light: '#282a36' },
    markdownHeading: { dark: 'purple', light: 'purple' },
    markdownLink: { dark: 'cyan', light: 'cyan' },
    markdownLinkText: { dark: 'pink', light: 'pink' },
    markdownCode: { dark: 'green', light: 'green' },
    markdownBlockQuote: { dark: 'comment', light: '#6272a4' },
    markdownEmph: { dark: 'yellow', light: 'yellow' },
    markdownStrong: { dark: 'orange', light: 'orange' },
    markdownHorizontalRule: { dark: 'comment', light: '#6272a4' },
    markdownListItem: { dark: 'purple', light: 'purple' },
    markdownListEnumeration: { dark: 'cyan', light: 'cyan' },
    markdownImage: { dark: 'cyan', light: 'cyan' },
    markdownImageText: { dark: 'pink', light: 'pink' },
    markdownCodeBlock: { dark: 'foreground', light: '#282a36' },
    syntaxComment: { dark: 'comment', light: '#6272a4' },
    syntaxKeyword: { dark: 'pink', light: 'pink' },
    syntaxFunction: { dark: 'green', light: 'green' },
    syntaxVariable: { dark: 'foreground', light: '#282a36' },
    syntaxString: { dark: 'yellow', light: 'yellow' },
    syntaxNumber: { dark: 'purple', light: 'purple' },
    syntaxType: { dark: 'cyan', light: 'cyan' },
    syntaxOperator: { dark: 'pink', light: 'pink' },
    syntaxPunctuation: { dark: 'foreground', light: '#282a36' },
  },
}

// ── Tokyo Night ─────────────────────────────────────────────────────────
const tokyonight: ThemeDefinition = {
  defs: {
    darkStep1: '#1a1b26', darkStep2: '#1e2030', darkStep3: '#222436',
    darkStep4: '#292e42', darkStep5: '#3b4261', darkStep6: '#545c7e',
    darkStep7: '#737aa2', darkStep8: '#9099b2', darkStep9: '#82aaff',
    darkStep10: '#89b4fa', darkStep11: '#828bb8', darkStep12: '#c8d3f5',
    darkRed: '#ff757f', darkOrange: '#ff966c', darkYellow: '#ffc777',
    darkGreen: '#c3e88d', darkCyan: '#86e1fc', darkPurple: '#c099ff',
    lightStep1: '#e1e2e7', lightStep2: '#d5d6db', lightStep3: '#c8c9ce',
    lightStep4: '#b9bac1', lightStep5: '#a8aecb', lightStep6: '#9699a8',
    lightStep7: '#737a8c', lightStep8: '#5a607d', lightStep9: '#2e7de9',
    lightStep10: '#1a6ce7', lightStep11: '#8990a3', lightStep12: '#3760bf',
    lightRed: '#f52a65', lightOrange: '#b15c00', lightYellow: '#8c6c3e',
    lightGreen: '#587539', lightCyan: '#007197', lightPurple: '#9854f1',
  },
  theme: {
    primary: { dark: 'darkStep9', light: 'lightStep9' },
    secondary: { dark: 'darkPurple', light: 'lightPurple' },
    accent: { dark: 'darkOrange', light: 'lightOrange' },
    error: { dark: 'darkRed', light: 'lightRed' },
    warning: { dark: 'darkOrange', light: 'lightOrange' },
    success: { dark: 'darkGreen', light: 'lightGreen' },
    info: { dark: 'darkStep9', light: 'lightStep9' },
    text: { dark: 'darkStep12', light: 'lightStep12' },
    textMuted: { dark: 'darkStep11', light: 'lightStep11' },
    background: { dark: 'darkStep1', light: 'lightStep1' },
    backgroundPanel: { dark: 'darkStep2', light: 'lightStep2' },
    backgroundElement: { dark: 'darkStep3', light: 'lightStep3' },
    border: { dark: 'darkStep7', light: 'lightStep7' },
    borderActive: { dark: 'darkStep8', light: 'lightStep8' },
    borderSubtle: { dark: 'darkStep6', light: 'lightStep6' },
    diffAdded: { dark: '#4fd6be', light: '#1e725c' },
    diffRemoved: { dark: '#c53b53', light: '#c53b53' },
    diffContext: { dark: '#828bb8', light: '#7086b5' },
    diffHunkHeader: { dark: '#828bb8', light: '#7086b5' },
    diffHighlightAdded: { dark: '#b8db87', light: '#4db380' },
    diffHighlightRemoved: { dark: '#e26a75', light: '#f52a65' },
    diffAddedBg: { dark: '#20303b', light: '#d5e5d5' },
    diffRemovedBg: { dark: '#37222c', light: '#f7d8db' },
    diffContextBg: { dark: 'darkStep2', light: 'lightStep2' },
    diffLineNumber: { dark: 'darkStep3', light: 'lightStep3' },
    diffAddedLineNumberBg: { dark: '#1b2b34', light: '#c5d5c5' },
    diffRemovedLineNumberBg: { dark: '#2d1f26', light: '#e7c8cb' },
    markdownText: { dark: 'darkStep12', light: 'lightStep12' },
    markdownHeading: { dark: 'darkPurple', light: 'lightPurple' },
    markdownLink: { dark: 'darkStep9', light: 'lightStep9' },
    markdownLinkText: { dark: 'darkCyan', light: 'lightCyan' },
    markdownCode: { dark: 'darkGreen', light: 'lightGreen' },
    markdownBlockQuote: { dark: 'darkYellow', light: 'lightYellow' },
    markdownEmph: { dark: 'darkYellow', light: 'lightYellow' },
    markdownStrong: { dark: 'darkOrange', light: 'lightOrange' },
    markdownHorizontalRule: { dark: 'darkStep11', light: 'lightStep11' },
    markdownListItem: { dark: 'darkStep9', light: 'lightStep9' },
    markdownListEnumeration: { dark: 'darkCyan', light: 'lightCyan' },
    markdownImage: { dark: 'darkStep9', light: 'lightStep9' },
    markdownImageText: { dark: 'darkCyan', light: 'lightCyan' },
    markdownCodeBlock: { dark: 'darkStep12', light: 'lightStep12' },
    syntaxComment: { dark: 'darkStep11', light: 'lightStep11' },
    syntaxKeyword: { dark: 'darkPurple', light: 'lightPurple' },
    syntaxFunction: { dark: 'darkStep9', light: 'lightStep9' },
    syntaxVariable: { dark: 'darkRed', light: 'lightRed' },
    syntaxString: { dark: 'darkGreen', light: 'lightGreen' },
    syntaxNumber: { dark: 'darkOrange', light: 'lightOrange' },
    syntaxType: { dark: 'darkYellow', light: 'lightYellow' },
    syntaxOperator: { dark: 'darkCyan', light: 'lightCyan' },
    syntaxPunctuation: { dark: 'darkStep12', light: 'lightStep12' },
  },
}

// ── Gruvbox ─────────────────────────────────────────────────────────────
const gruvbox: ThemeDefinition = {
  defs: {
    darkBg0: '#282828', darkBg1: '#3c3836', darkBg2: '#504945',
    darkBg3: '#665c54', darkFg0: '#fbf1c7', darkFg1: '#ebdbb2',
    darkGray: '#928374', darkRed: '#cc241d', darkGreen: '#98971a',
    darkYellow: '#d79921', darkBlue: '#458588', darkPurple: '#b16286',
    darkAqua: '#689d6a', darkOrange: '#d65d0e', darkRedBright: '#fb4934',
    darkGreenBright: '#b8bb26', darkYellowBright: '#fabd2f',
    darkBlueBright: '#83a598', darkPurpleBright: '#d3869b',
    darkAquaBright: '#8ec07c', darkOrangeBright: '#fe8019',
    lightBg0: '#fbf1c7', lightBg1: '#ebdbb2', lightBg2: '#d5c4a1',
    lightBg3: '#bdae93', lightFg0: '#282828', lightFg1: '#3c3836',
    lightGray: '#7c6f64', lightRed: '#9d0006', lightGreen: '#79740e',
    lightYellow: '#b57614', lightBlue: '#076678', lightPurple: '#8f3f71',
    lightAqua: '#427b58', lightOrange: '#af3a03',
  },
  theme: {
    primary: { dark: 'darkBlueBright', light: 'lightBlue' },
    secondary: { dark: 'darkPurpleBright', light: 'lightPurple' },
    accent: { dark: 'darkAquaBright', light: 'lightAqua' },
    error: { dark: 'darkRedBright', light: 'lightRed' },
    warning: { dark: 'darkOrangeBright', light: 'lightOrange' },
    success: { dark: 'darkGreenBright', light: 'lightGreen' },
    info: { dark: 'darkYellowBright', light: 'lightYellow' },
    text: { dark: 'darkFg1', light: 'lightFg1' },
    textMuted: { dark: 'darkGray', light: 'lightGray' },
    background: { dark: 'darkBg0', light: 'lightBg0' },
    backgroundPanel: { dark: 'darkBg1', light: 'lightBg1' },
    backgroundElement: { dark: 'darkBg2', light: 'lightBg2' },
    border: { dark: 'darkBg3', light: 'lightBg3' },
    borderActive: { dark: 'darkFg1', light: 'lightFg1' },
    borderSubtle: { dark: 'darkBg2', light: 'lightBg2' },
    diffAdded: { dark: 'darkGreen', light: 'lightGreen' },
    diffRemoved: { dark: 'darkRed', light: 'lightRed' },
    diffContext: { dark: 'darkGray', light: 'lightGray' },
    diffHunkHeader: { dark: 'darkAqua', light: 'lightAqua' },
    diffHighlightAdded: { dark: 'darkGreenBright', light: 'lightGreen' },
    diffHighlightRemoved: { dark: 'darkRedBright', light: 'lightRed' },
    diffAddedBg: { dark: '#32302f', light: '#dcd8a4' },
    diffRemovedBg: { dark: '#322929', light: '#e2c7c3' },
    diffContextBg: { dark: 'darkBg1', light: 'lightBg1' },
    diffLineNumber: { dark: 'darkBg3', light: 'lightBg3' },
    diffAddedLineNumberBg: { dark: '#2a2827', light: '#cec99e' },
    diffRemovedLineNumberBg: { dark: '#2a2222', light: '#d3bdb9' },
    markdownText: { dark: 'darkFg1', light: 'lightFg1' },
    markdownHeading: { dark: 'darkBlueBright', light: 'lightBlue' },
    markdownLink: { dark: 'darkAquaBright', light: 'lightAqua' },
    markdownLinkText: { dark: 'darkGreenBright', light: 'lightGreen' },
    markdownCode: { dark: 'darkYellowBright', light: 'lightYellow' },
    markdownBlockQuote: { dark: 'darkGray', light: 'lightGray' },
    markdownEmph: { dark: 'darkPurpleBright', light: 'lightPurple' },
    markdownStrong: { dark: 'darkOrangeBright', light: 'lightOrange' },
    markdownHorizontalRule: { dark: 'darkGray', light: 'lightGray' },
    markdownListItem: { dark: 'darkBlueBright', light: 'lightBlue' },
    markdownListEnumeration: { dark: 'darkAquaBright', light: 'lightAqua' },
    markdownImage: { dark: 'darkAquaBright', light: 'lightAqua' },
    markdownImageText: { dark: 'darkGreenBright', light: 'lightGreen' },
    markdownCodeBlock: { dark: 'darkFg1', light: 'lightFg1' },
    syntaxComment: { dark: 'darkGray', light: 'lightGray' },
    syntaxKeyword: { dark: 'darkRedBright', light: 'lightRed' },
    syntaxFunction: { dark: 'darkGreenBright', light: 'lightGreen' },
    syntaxVariable: { dark: 'darkBlueBright', light: 'lightBlue' },
    syntaxString: { dark: 'darkYellowBright', light: 'lightYellow' },
    syntaxNumber: { dark: 'darkPurpleBright', light: 'lightPurple' },
    syntaxType: { dark: 'darkAquaBright', light: 'lightAqua' },
    syntaxOperator: { dark: 'darkOrangeBright', light: 'lightOrange' },
    syntaxPunctuation: { dark: 'darkFg1', light: 'lightFg1' },
  },
}

// ── Solarized ───────────────────────────────────────────────────────────
const solarized: ThemeDefinition = {
  defs: {
    base03: '#002b36', base02: '#073642', base01: '#586e75',
    base00: '#657b83', base0: '#839496', base1: '#93a1a1',
    base2: '#eee8d5', base3: '#fdf6e3', yellow: '#b58900',
    orange: '#cb4b16', red: '#dc322f', magenta: '#d33682',
    violet: '#6c71c4', blue: '#268bd2', cyan: '#2aa198', green: '#859900',
  },
  theme: {
    primary: { dark: 'blue', light: 'blue' },
    secondary: { dark: 'violet', light: 'violet' },
    accent: { dark: 'cyan', light: 'cyan' },
    error: { dark: 'red', light: 'red' },
    warning: { dark: 'yellow', light: 'yellow' },
    success: { dark: 'green', light: 'green' },
    info: { dark: 'orange', light: 'orange' },
    text: { dark: 'base0', light: 'base00' },
    textMuted: { dark: 'base01', light: 'base1' },
    background: { dark: 'base03', light: 'base3' },
    backgroundPanel: { dark: 'base02', light: 'base2' },
    backgroundElement: { dark: '#073642', light: '#eee8d5' },
    border: { dark: 'base02', light: 'base2' },
    borderActive: { dark: 'base01', light: 'base1' },
    borderSubtle: { dark: '#073642', light: '#eee8d5' },
    diffAdded: { dark: 'green', light: 'green' },
    diffRemoved: { dark: 'red', light: 'red' },
    diffContext: { dark: 'base01', light: 'base1' },
    diffHunkHeader: { dark: 'base01', light: 'base1' },
    diffHighlightAdded: { dark: 'green', light: 'green' },
    diffHighlightRemoved: { dark: 'red', light: 'red' },
    diffAddedBg: { dark: '#073642', light: '#eee8d5' },
    diffRemovedBg: { dark: '#073642', light: '#eee8d5' },
    diffContextBg: { dark: 'base02', light: 'base2' },
    diffLineNumber: { dark: 'base01', light: 'base1' },
    diffAddedLineNumberBg: { dark: '#073642', light: '#eee8d5' },
    diffRemovedLineNumberBg: { dark: '#073642', light: '#eee8d5' },
    markdownText: { dark: 'base0', light: 'base00' },
    markdownHeading: { dark: 'blue', light: 'blue' },
    markdownLink: { dark: 'cyan', light: 'cyan' },
    markdownLinkText: { dark: 'violet', light: 'violet' },
    markdownCode: { dark: 'green', light: 'green' },
    markdownBlockQuote: { dark: 'base01', light: 'base1' },
    markdownEmph: { dark: 'yellow', light: 'yellow' },
    markdownStrong: { dark: 'orange', light: 'orange' },
    markdownHorizontalRule: { dark: 'base01', light: 'base1' },
    markdownListItem: { dark: 'blue', light: 'blue' },
    markdownListEnumeration: { dark: 'cyan', light: 'cyan' },
    markdownImage: { dark: 'cyan', light: 'cyan' },
    markdownImageText: { dark: 'violet', light: 'violet' },
    markdownCodeBlock: { dark: 'base0', light: 'base00' },
    syntaxComment: { dark: 'base01', light: 'base1' },
    syntaxKeyword: { dark: 'green', light: 'green' },
    syntaxFunction: { dark: 'blue', light: 'blue' },
    syntaxVariable: { dark: 'cyan', light: 'cyan' },
    syntaxString: { dark: 'cyan', light: 'cyan' },
    syntaxNumber: { dark: 'magenta', light: 'magenta' },
    syntaxType: { dark: 'yellow', light: 'yellow' },
    syntaxOperator: { dark: 'green', light: 'green' },
    syntaxPunctuation: { dark: 'base0', light: 'base00' },
  },
}

// ── Nord ────────────────────────────────────────────────────────────────
const nord: ThemeDefinition = {
  defs: {
    nord0: '#2E3440', nord1: '#3B4252', nord2: '#434C5E', nord3: '#4C566A',
    nord4: '#D8DEE9', nord5: '#E5E9F0', nord6: '#ECEFF4',
    nord7: '#8FBCBB', nord8: '#88C0D0', nord9: '#81A1C1', nord10: '#5E81AC',
    nord11: '#BF616A', nord12: '#D08770', nord13: '#EBCB8B', nord14: '#A3BE8C',
    nord15: '#B48EAD',
  },
  theme: {
    primary: { dark: 'nord8', light: 'nord10' },
    secondary: { dark: 'nord9', light: 'nord9' },
    accent: { dark: 'nord7', light: 'nord7' },
    error: { dark: 'nord11', light: 'nord11' },
    warning: { dark: 'nord12', light: 'nord12' },
    success: { dark: 'nord14', light: 'nord14' },
    info: { dark: 'nord8', light: 'nord10' },
    text: { dark: 'nord6', light: 'nord0' },
    textMuted: { dark: '#8B95A7', light: 'nord1' },
    background: { dark: 'nord0', light: 'nord6' },
    backgroundPanel: { dark: 'nord1', light: 'nord5' },
    backgroundElement: { dark: 'nord2', light: 'nord4' },
    border: { dark: 'nord2', light: 'nord3' },
    borderActive: { dark: 'nord3', light: 'nord2' },
    borderSubtle: { dark: 'nord2', light: 'nord3' },
    diffAdded: { dark: 'nord14', light: 'nord14' },
    diffRemoved: { dark: 'nord11', light: 'nord11' },
    diffContext: { dark: '#8B95A7', light: 'nord3' },
    diffHunkHeader: { dark: '#8B95A7', light: 'nord3' },
    diffHighlightAdded: { dark: 'nord14', light: 'nord14' },
    diffHighlightRemoved: { dark: 'nord11', light: 'nord11' },
    diffAddedBg: { dark: '#3B4252', light: '#E5E9F0' },
    diffRemovedBg: { dark: '#3B4252', light: '#E5E9F0' },
    diffContextBg: { dark: 'nord1', light: 'nord5' },
    diffLineNumber: { dark: 'nord2', light: 'nord4' },
    diffAddedLineNumberBg: { dark: '#3B4252', light: '#E5E9F0' },
    diffRemovedLineNumberBg: { dark: '#3B4252', light: '#E5E9F0' },
    markdownText: { dark: 'nord4', light: 'nord0' },
    markdownHeading: { dark: 'nord8', light: 'nord10' },
    markdownLink: { dark: 'nord9', light: 'nord9' },
    markdownLinkText: { dark: 'nord7', light: 'nord7' },
    markdownCode: { dark: 'nord14', light: 'nord14' },
    markdownBlockQuote: { dark: '#8B95A7', light: 'nord3' },
    markdownEmph: { dark: 'nord12', light: 'nord12' },
    markdownStrong: { dark: 'nord13', light: 'nord13' },
    markdownHorizontalRule: { dark: '#8B95A7', light: 'nord3' },
    markdownListItem: { dark: 'nord8', light: 'nord10' },
    markdownListEnumeration: { dark: 'nord7', light: 'nord7' },
    markdownImage: { dark: 'nord9', light: 'nord9' },
    markdownImageText: { dark: 'nord7', light: 'nord7' },
    markdownCodeBlock: { dark: 'nord4', light: 'nord0' },
    syntaxComment: { dark: '#8B95A7', light: 'nord3' },
    syntaxKeyword: { dark: 'nord9', light: 'nord9' },
    syntaxFunction: { dark: 'nord8', light: 'nord8' },
    syntaxVariable: { dark: 'nord7', light: 'nord7' },
    syntaxString: { dark: 'nord14', light: 'nord14' },
    syntaxNumber: { dark: 'nord15', light: 'nord15' },
    syntaxType: { dark: 'nord7', light: 'nord7' },
    syntaxOperator: { dark: 'nord9', light: 'nord9' },
    syntaxPunctuation: { dark: 'nord4', light: 'nord0' },
  },
}

// ── Registry ────────────────────────────────────────────────────────────

const THEME_DEFS: Record<MythosThemeName, ThemeDefinition> = {
  opencode,
  'catppuccin-mocha': catppuccin,
  'catppuccin-latte': catppuccin,
  dracula,
  tokyonight,
  gruvbox,
  solarized,
  nord,
}

/** Default dark/light for each theme name */
const THEME_MODES: Record<MythosThemeName, boolean> = {
  opencode: true,             // dark (default)
  'catppuccin-mocha': true,   // dark
  'catppuccin-latte': false,  // light
  dracula: true,
  tokyonight: true,
  gruvbox: true,
  solarized: true,
  nord: true,
}

const cache = new Map<string, MythosTheme>()

/**
 * Get a resolved MythosTheme by name.
 * Uses the theme's default dark/light mode unless overridden.
 */
export function getMythosTheme(
  name: MythosThemeName,
  isDark?: boolean,
): MythosTheme {
  const dark = isDark ?? THEME_MODES[name]
  const key = `${name}:${dark}`
  let theme = cache.get(key)
  if (!theme) {
    theme = resolveTheme(name, THEME_DEFS[name]!, dark)
    cache.set(key, theme)
  }
  return theme
}
